name: Reservmed CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: '**/*.csproj'

    - name: Install dependencies
      run: dotnet restore

    - name: Run build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish
    
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: reservmed-app
        path: ./publish
